-- Sarah-Too-Doo data model
-- Simulated tables for the to-do list application.
-- Not deployed automatically -- run against the target schema when ready.

create table todo_list_groups (
    group_id         number generated by default on null as identity
                         constraint todo_list_groups_pk primary key,
    group_name       varchar2(200 char) not null,
    display_order    number default 10 not null,
    created_by       varchar2(255 char),
    created_on       date,
    updated_by       varchar2(255 char),
    updated_on       date,
    constraint todo_list_groups_name_uk unique (group_name)
);

create table todo_lists (
    list_id          number generated by default on null as identity
                         constraint todo_lists_pk primary key,
    list_name        varchar2(200 char) not null,
    group_id         number
                         constraint todo_lists_group_fk
                         references todo_list_groups (group_id) on delete set null,
    display_order    number default 10 not null,
    created_by       varchar2(255 char),
    created_on       date,
    updated_by       varchar2(255 char),
    updated_on       date,
    constraint todo_lists_name_uk unique (list_name)
);

create index todo_lists_group_id_ix on todo_lists (group_id);

create table todo_tasks (
    task_id          number generated by default on null as identity
                         constraint todo_tasks_pk primary key,
    list_id          number not null
                         constraint todo_tasks_list_fk
                         references todo_lists (list_id) on delete cascade,
    task_name        varchar2(500 char) not null,
    is_complete      varchar2(1 char) default 'N' not null
                         constraint todo_tasks_complete_ck check (is_complete in ('Y', 'N')),
    display_order    number default 10 not null,
    completed_on     timestamp,
    created_by       varchar2(255 char),
    created_on       date,
    updated_by       varchar2(255 char),
    updated_on       date
);

create index todo_tasks_list_id_ix on todo_tasks (list_id);
